### ISSUE TITLE
Javascript error when no content blocks available for section

### ISSUE THREAD

**Issue by abeyer** [Salesforce-org-Impact-Labs/GrantGuides#75]
**OVERVIEW**
When a new section does not have any content blocks available and a user clicks the 'Add Block' button in editor the block selection lwc displays a 'No content blocks available' message but alsothrows a javascript error: `Cannot read properties of undefined (reading 'sectionname')`

**ACCEPTANCE CRITERIA**
No javascript error

**OUT OF SCOPE**

**BACKGROUND/REFERENCE**

**Comment by abeyer** [comment]
When checking for data returned, need to confirm that the list is not empty:
https://github.com/Salesforce-org-Impact-Labs/GrantGuides/blob/3e29dfb900b7c0032f6b8e35f8ff044168f58b1d/force-app/main/default/lwc/ggwContentBlockModal/ggwContentBlockModal.js#L20

**Comment by iandrosov** [comment]
Fixed in commit for #81 bug81
