### ISSUE TITLE
Apex test failing

### ISSUE THREAD

**Issue by cidarm** [Salesforce-org-Impact-Labs/GrantGuides#81]
**OVERVIEW**
The updates to the SOQL statements in the class caused some failures in the Apex tests.
**ACCEPTANCE CRITERIA**
The Package must have at least 75% before release the package.
**OUT OF SCOPE**

**BACKGROUND/REFERENCE**
`=== Test Summary
NAME                 VALUE                        
───────────────────  ─────────────────────────────
Outcome              Failed                       
Tests Ran            19                           
Pass Rate            11%                          
Fail Rate            89%                          
Skip Rate            0%                           
Test Run Id          707DM00002JKU02              
Test Execution Time  435 ms                       
Org Id               00DDM000003rZjr2AE           
Username             test-0pdfxt5f0jmd@example.com
Org Wide Coverage    26%                          

=== Test Results
TEST NAME                                                OUTCOME  MESSAGE                                                                                                      RUNTIME (MS)
───────────────────────────────────────────────────────  ───────  ───────────────────────────────────────────────────────────────────────────────────────────────────────────  ────────────
GGW_ExportCtrlTest.testExportCtrl                        Fail     System.QueryException: Insufficient permissions: secure query included inaccessible field                    
                                                                  Class.GGW_ApplicationCtrl.getBlocksForSection: line 369, column 1                                            
                                                                  Class.GGW_ApplicationCtrl.getSections: line 315, column 1                                                    
                                                                  Class.GGW_ExportCtrlTest.testExportCtrl: line 65, column 1                                                               
GGW_ExportCtrlTest.testExportWithPage                    Fail     System.QueryException: Insufficient permissions: secure query included inaccessible field                    
                                                                  Class.GGW_ApplicationCtrl.getBlocksForSection: line 369, column 1                                            
                                                                  Class.GGW_ApplicationCtrl.getSections: line 315, column 1                                                    
                                                                  Class.GGW_ExportCtrlTest.testExportWithPage: line 91, column 1                                                           
GGW_ApplicationCtrlTest.testAddTextBlockToLibrary        Pass                                                                                                                  67          
GGW_ApplicationCtrlTest.testContentBlocks                Fail     System.QueryException: Insufficient permissions: secure query included inaccessible field                    
                                                                  Class.GGW_ApplicationCtrl.getContentBlocks: line 394, column 1                                               
                                                                  Class.GGW_ApplicationCtrlTest.testContentBlocks: line 126, column 1                                                      
GGW_ApplicationCtrlTest.testCreateNewSection             Fail     System.QueryException: Insufficient permissions: secure query included inaccessible field                    
                                                                  Class.GGW_ApplicationCtrl.createNewSection: line 188, column 1                                               
                                                                  Class.GGW_ApplicationCtrlTest.testCreateNewSection: line 149, column 1                                                   
GGW_ApplicationCtrlTest.testDeleteSectionItem            Fail     System.QueryException: Insufficient permissions: secure query included inaccessible field                    
                                                                  Class.GGW_ApplicationCtrl.getBlocksForSection: line 369, column 1                                            
                                                                  Class.GGW_ApplicationCtrl.getSections: line 315, column 1                                                    
                                                                  Class.GGW_ApplicationCtrlTest.testDeleteSectionItem: line 270, column 1                                                  
GGW_ApplicationCtrlTest.testFindSections                 Fail     System.QueryException: Insufficient permissions: secure query included inaccessible field                    
                                                                  Class.GGW_ApplicationCtrl.findSections: line 355, column 1                                                   
                                                                  Class.GGW_ApplicationCtrlTest.testFindSections: line 103, column 1                                                       
GGW_ApplicationCtrlTest.testGetApplication               Fail     System.QueryException: Insufficient permissions: secure query included inaccessible field                    
                                                                  Class.GGW_ApplicationCtrl.getBlocksForSection: line 369, column 1                                            
                                                                  Class.GGW_ApplicationCtrl.getSections: line 315, column 1                                                    
                                                                  Class.GGW_ApplicationCtrlTest.testGetApplication: line 166, column 1                                                     
GGW_ApplicationCtrlTest.testGetSections                  Fail     System.QueryException: Insufficient permissions: secure query included inaccessible field                    
                                                                  Class.GGW_ApplicationCtrl.getBlocksForSection: line 369, column 1                                            
                                                                  Class.GGW_ApplicationCtrl.getSections: line 315, column 1                                                    
                                                                  Class.GGW_ApplicationCtrlTest.testGetSections: line 117, column 1                                                        
GGW_ApplicationCtrlTest.testNewGrant                     Fail     System.QueryException: Insufficient permissions: secure query included inaccessible field                    
                                                                  Class.GGW_ApplicationCtrl.getBlocksForSection: line 369, column 1                                            
                                                                  Class.GGW_ApplicationCtrl.getSections: line 315, column 1                                                    
                                                                  Class.GGW_ApplicationCtrlTest.testNewGrant: line 78, column 1                                                            
GGW_ApplicationCtrlTest.testReorderSections              Fail     System.QueryException: Insufficient permissions: secure query included inaccessible field                    
                                                                  Class.GGW_ApplicationCtrl.getBlocksForSection: line 369, column 1                                            
                                                                  Class.GGW_ApplicationCtrl.getSections: line 315, column 1                                                    
                                                                  Class.GGW_ApplicationCtrlTest.testReorderSections: line 213, column 1                                                    
GGW_ApplicationCtrlTest.testSaveSelectedSectionText      Fail     System.QueryException: Insufficient permissions: secure query included inaccessible field                    
                                                                  Class.GGW_ApplicationCtrl.getBlocksForSection: line 369, column 1                                            
                                                                  Class.GGW_ApplicationCtrl.getSections: line 315, column 1                                                    
                                                                  Class.GGW_ApplicationCtrlTest.testSaveSelectedSectionText: line 188, column 1                                            
GGW_ApplicationCtrlTest.testUpdateSelectedItemText       Fail     System.QueryException: Insufficient permissions: secure query included inaccessible field                    
                                                                  Class.GGW_ApplicationCtrl.getBlocksForSection: line 369, column 1                                            
                                                                  Class.GGW_ApplicationCtrl.getSections: line 315, column 1                                                    
                                                                  Class.GGW_ApplicationCtrlTest.testUpdateSelectedItemText: line 243, column 1                                             
GGW_UtilTest.testExistingGrantState                      Fail     System.QueryException: Insufficient permissions: secure query included inaccessible field                    
                                                                  Class.GGW_ApplicationCtrl.getBlocksForSection: line 369, column 1                                            
                                                                  Class.GGW_ApplicationCtrl.getSections: line 315, column 1                                                    
                                                                  Class.GGW_UtilTest.testExistingGrantState: line 111, column 1                                                            
GGW_UtilTest.testGetSelectedItems                        Fail     System.QueryException: Insufficient permissions: secure query included inaccessible field                    
                                                                  Class.GGW_ApplicationCtrl.getBlocksForSection: line 369, column 1                                            
                                                                  Class.GGW_ApplicationCtrl.getSections: line 315, column 1                                                    
                                                                  Class.GGW_UtilTest.testGetSelectedItems: line 145, column 1                                                              
GGW_UtilTest.testNewsaveGrantState                       Fail     System.QueryException: Insufficient permissions: secure query included inaccessible field                    
                                                                  Class.GGW_ApplicationCtrl.getBlocksForSection: line 369, column 1                                            
                                                                  Class.GGW_ApplicationCtrl.getSections: line 315, column 1                                                    
                                                                  Class.GGW_UtilTest.testNewsaveGrantState: line 77, column 1                                                              
GGW_UtilTest.testQueryGrantApp                           Fail     System.QueryException: Insufficient permissions: secure query included inaccessible field                    
                                                                  Class.GGW_ApplicationCtrl.getBlocksForSection: line 369, column 1                                            
                                                                  Class.GGW_ApplicationCtrl.getSections: line 315, column 1                                                    
                                                                  Class.GGW_UtilTest.testQueryGrantApp: line 163, column 1                                                                 
GGW_SampleDataTest.testInsertSampleSections              Fail     System.AssertException: Assertion Failed: Sections list is expected to have records: Expected: 9, Actual: 8  
                                                                  Class.GGW_SampleDataTest.testInsertSampleSections: line 25, column 1                                                     
GGW_SampleDataTest.testInsertSampleSectionsWithExisting  Pass  `

**Comment by iandrosov** [comment]
Fixed Apex tests, it was oversight on use of WITH SECURITY SOQL https://developer.salesforce.com/docs/atlas.en-us.232.0.apexcode.meta/apexcode/apex_classes_with_security_enforced.htm. Not all tyopes query supported Traversing a polymorphic field’s relationship is not supported in queries using WITH SECURITY_ENFORCED. For example, you cannot use WITH SECURITY_ENFORCED in this query, which returns the Id and Owner names for User and Calendar entities: SELECT Id, What.Name FROM Event WHERE What.Type IN (’User’,’Calendar’).

**Comment by iandrosov** [comment]
New PR fixes this issue https://github.com/Salesforce-org-Impact-Labs/GrantGuides/pull/82
